First page`s site done
qsok3d/yard-frontend pull request #1
Opened 2017-06-27 21:27 UTC by qsok3d

Done fonts
Done css style
Done HTML style
Use flexbox, and flexboxgrid for footer.

2017-06-27 23:49 UTC, imevro requested changes

2017-06-27 23:49 UTC, evgenyrodionov commented on complexes.html
> +    <div class="header__container container">
мы не смешиваем свои классы и классы сетки

2017-06-27 23:49 UTC, evgenyrodionov commented on complexes.html
> +  <link rel="stylesheet" href="css/flexboxgrid.css" type="text/css">
фбг из сдн возьми

2017-06-27 23:49 UTC, evgenyrodionov commented on complexes.html
> +  <link rel="stylesheet" href="css/flexboxgrid.css" type="text/css">
тайп текст цсс из хтмл5 давно убран

2017-06-27 23:49 UTC, evgenyrodionov commented on complexes.html
> +  <meta http-equiv="X-UA-Compatible" content="ie=edge">
что значит эта строчка? это вопрос

2017-06-27 23:49 UTC, evgenyrodionov commented on complexes.html
> +  <title>Document</title>
слабый тайтл

2017-06-27 23:49 UTC, evgenyrodionov commented on complexes.html
> +      <nav class="main__menu">
меню?

2017-06-27 23:49 UTC, evgenyrodionov commented on complexes.html
> +          <div class="main__card card">
а зачем тут два класса

2017-06-27 23:49 UTC, evgenyrodionov commented on complexes.html
> +            <p class="details__text">ОГРН 1175074002531</p>
footer footer__nav details__text? согласованности нет

2017-06-27 23:49 UTC, evgenyrodionov commented on style.css
> +*{
нет, поставь нормалайз, оч хуевый селектор и очень хуевые правила в нем

2017-06-27 23:49 UTC, evgenyrodionov commented on style.css
> +    padding: 0;
откуда 4 пробела вместо 2

2017-06-27 23:49 UTC, evgenyrodionov commented on style.css
> +    width: 1440px;
зачем?

2017-06-27 23:49 UTC, evgenyrodionov commented on style.css
> +.container{
в фбг есть свой

2017-06-28 20:43 UTC, qsok3d commented on complexes.html
> +  <meta http-equiv="X-UA-Compatible" content="ie=edge">
IE=edge при заходе через IE указывает браузеру включать поддержку максимально доступной версии

2017-06-29 10:42 UTC, evgenyrodionov commented on complexes.html
> +  <meta http-equiv="X-UA-Compatible" content="ie=edge">
https://stackoverflow.com/a/6771584/2389634

2017-06-29 10:45 UTC, evgenyrodionov commented
https://rawgit.com/qsok3d/yard-frontend/develop/complexes.html

![image](https://user-images.githubusercontent.com/775692/27684045-f1a1c400-5cd0-11e7-953f-4d8e7dbef12b.png)
![image](https://user-images.githubusercontent.com/775692/27684061-fbe2f57e-5cd0-11e7-8f12-84e5e7e60aad.png)
![image](https://user-images.githubusercontent.com/775692/27684096-1cb8f050-5cd1-11e7-83ff-d0a38f74d81d.png)

2017-06-29 21:13 UTC, evgenyrodionov commented
Чтобы шрифты были норм, повесь на бади 
```
text-rendering: optimizeLegibility !important;
  -webkit-font-smoothing: antialiased;
```

2017-06-29 21:16 UTC, imevro requested changes

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +      <div class="header__wrapp">
wrapp?

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +      <div class="banner__wrapper">
через сетку сделай

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +          <h2 class="main__title">Discover Our New Developments</h2>
не понял как баннер или промоблок сочетается с main

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +        <nav class="main__list">
почему нав

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +          <a href="#" class="main__link">
линк на что?

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +            <div class="main__card">
зачем этот враппер?

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +            <div class="main__card main__card_hover">
что за класс ховер? речь была про :hover селектор

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +            <nav class="footer__details">
почему это нав? навигация по чему?

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +              <a href="" class="products__link">Садовые кварталы</a>
что за продактс? и как footer_ привёл к products?

2017-06-29 21:16 UTC, evgenyrodionov commented on complexes.html
> +  <link rel="stylesheet" href="css/normalize.css">
сдн

2017-06-29 21:36 UTC, qsok3d commented on complexes.html
> +  <link rel="stylesheet" href="css/normalize.css">
+

2017-06-29 21:53 UTC, qsok3d commented on complexes.html
> +      <div class="header__wrapp">
+

2017-06-29 21:53 UTC, qsok3d commented on complexes.html
> +      <div class="banner__wrapper">
+

2017-06-29 22:05 UTC, qsok3d commented on complexes.html
> +          <h2 class="main__title">Discover Our New Developments</h2>
+

2017-06-29 22:05 UTC, qsok3d commented on complexes.html
> +            <div class="main__card main__card_hover">
+

2017-06-29 22:23 UTC, qsok3d commented on complexes.html
> +          <h2 class="main__title">Discover Our New Developments</h2>
+

2017-06-29 22:23 UTC, qsok3d commented on complexes.html
> +        <nav class="main__list">
+

2017-06-29 22:23 UTC, qsok3d commented on complexes.html
> +          <a href="#" class="main__link">
+

2017-06-29 22:31 UTC, qsok3d commented on complexes.html
> +              <a href="" class="products__link">Садовые кварталы</a>
+

2017-06-29 22:31 UTC, qsok3d commented on complexes.html
> +            <nav class="footer__details">
+

2017-06-29 22:40 UTC, qsok3d commented on complexes.html
> +            <div class="main__card">
+

2017-06-30 09:52 UTC, evgenyrodionov commented
Я не вижу исправления и коммитов вообще после моего ревью

2017-06-30 19:26 UTC, imevro requested changes
плохой несогласованный нейминг, смотри чужие ПРы

по макету норм

2017-07-01 09:36 UTC, imevro requested changes

2017-07-01 09:36 UTC, evgenyrodionov commented on complexes.html
> +      <div class="content__wrapper">
зачем если есть контейнер

2017-07-01 09:36 UTC, evgenyrodionov commented on complexes.html
> +        <div class="content__banner__caption">
зачем этот префикс контент?

2017-07-01 09:36 UTC, evgenyrodionov commented on complexes.html
> +          <a href="#" class="content__complexe__link">
complexe? это на каком?

2017-07-01 09:36 UTC, evgenyrodionov commented on complexes.html
> +            <div class="content__complexe__card">
зачем этот див в ссылке?

2017-07-01 09:36 UTC, evgenyrodionov commented on complexes.html
> +                <p class="complexe__card__subtitle">SOUTH BEACH, SAN FRANCISCO</p>
это не сабтайтл, это район

2017-07-01 09:36 UTC, evgenyrodionov commented on complexes.html
> +                <p class="complexe__card__text">The Lewis Steel Building is a masterful industrial conversion located in the heart of Williamsburg. Located at 76 North 4th Street, the former 1930's s
это описание ЖК, а не текст

2017-07-01 09:36 UTC, evgenyrodionov commented on complexes.html
> +              <h4 class="footer__about__title">Компания</h4>
чем отличается от footer__complexes__title или footer__info__title?

2017-07-01 09:37 UTC, evgenyrodionov commented
название файла combined-shape.png это дно, раз
мы работаем с свг, два

2017-07-01 14:05 UTC, imevro requested changes

2017-07-01 14:05 UTC, evgenyrodionov commented on complexes.html
> +        <a href="#" class="complexes__link">
почему блок уехал на 2 пробела вправо

2017-07-01 14:05 UTC, evgenyrodionov commented on complexes.html
> +          <span class="complexes__card__info">
почему тут спан, если это инлайновый элемент

2017-07-01 14:05 UTC, evgenyrodionov commented on complexes.html
> +          <img src="img/card-pic.jpg" alt="" class="complexes__card__pic" width="490" height="350">
ширину высоту задаем в цсс, а не атрибутами

2017-07-01 14:05 UTC, evgenyrodionov commented on complexes.html
> +        <a href="#" class="complexes__link">
почему complexes?

2017-07-01 14:05 UTC, evgenyrodionov commented on complexes.html
> +            <p class="card__info__disctrict">SOUTH BEACH, SAN FRANCISCO</p>
в какой момент complexes_card стала просто card?

2017-07-01 17:31 UTC, imevro requested changes
что за комплексе

2017-07-02 11:34 UTC, imevro approved these changes

2017-07-04 17:26 UTC, merged

2017-07-04 17:26 UTC, evgenyrodionov commented
гит фетч --олл, гит чекаут мастер, гит пулл --ребейз и новый бранч от мастера